version: "3.5"
volumes:
  node-db:
  shared: 
services:
  dev:
    image: robertinoiog/kenya_course:v4
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace
      - shared:/ipc
    environment:
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - NETWORK=preprod
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  node:
    environment:
      - NETWORK=preprod
    healthcheck:
      interval: 10s
      retries: 10
      test: socat -u OPEN:/dev/null UNIX-CONNECT:/ipc/node.socket
      timeout: 5s
    image: inputoutput/cardano-node:8.1.2
    restart: unless-stopped
    volumes:
      - shared:/ipc
      - node-db:/data
