name: "Tests"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
            nix_path: nixpkgs=channel:nixos-unstable
            extra_nix_config: |
              allowed-uris = https://github.com/NixOS/nixpkgs https://github.com/input-output-hk https://github.com/NixOS/nixpkgs-channels
              trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
              substituters = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
      - run: nix-build test-nix-expresion.nix --restrict-eval -I . -A required --no-out-link
      #- run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
